### ISSUE TITLE
Top spacing in the sticky TOC

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-developer#406] opened 2023-11-23 09:31 UTC
Before scrolling a page [like this one](https://developer.wordpress.org/redesign-test/cli/commands/), the TOC is aligned with the h1 element. But once you scroll down, the TOC leaves an empty space in the top that looks broken or buggy. 

https://github.com/WordPress/wporg-developer/assets/895819/ca7416d1-8298-49d7-975e-bd990ba1b897

## Idea

I played with Firefox's inspector, and `-60px` in `--wp--custom--wporg-sidebar-container--spacing--margin--top` seems to work well for the fixed position. Here is what it looks like.

https://github.com/WordPress/wporg-developer/assets/895819/5aa182f6-69cc-4d8c-a0fe-732c5010cf9e

**Comment by adamwoodnz** [comment] 2023-11-26 22:19
Duplicate of WordPress/wporg-mu-plugins#524, but I'll note this comment there, thanks

**Closed as not planned by adamwoodnz** 2023-11-26 22:19 UTC
Labels: Redesign
