### ISSUE TITLE
TOC isn't position fixed when if it's too long

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-developer#365] opened 2023-11-13 08:45 UTC
Too much content makes the TOC long and not position-fixed anymore.
It should be scrollable as well as having a fixed position.

Example: https://developer.wordpress.org/redesign-test/reference/functions/register_post_type/#more-information

**Comment by adamwoodnz** [comment] 2023-11-14 20:02
This is by design, but maybe is worth reviewing, @WordPress/meta-design ?

**Comment by jasmussen** [comment] 2023-11-15 08:42
This was indeed by design, yes, but upon some reflection also partially detailed in #341 I think we can potentially revisit that design decision. That is, have both chapters (when available) and TOC be sticky and scroll with you down the page, have a max-height of 100% as well as `overflow: auto;` so those panels scroll independently when they need to. The main challenge here is the scrollbars will feel clunky, but I would think we can address that with [custom styles](https://github.com/WordPress/wporg-developer/issues/312#issuecomment-1794214460).

**Comment by fcoveram** [comment] 2023-11-15 09:47
I like how X (twitter) solves this sticky and overflow component, but not sure if it's similar to Joen's suggestion.

https://github.com/WordPress/wporg-developer/assets/895819/49df029d-3e96-4a0c-acc3-6917269e13c0

**Comment by adamwoodnz** [comment] 2023-11-15 20:37
I'm going to put this post-launch as I think it's too much of a lift for MVP

**Comment by joyously** [comment] 2023-11-23 01:35
When using a narrower window, the ToC is inline and closed. It scrolls with the content. Why? 
When the window is wider, it is on the right, open, and fixed position.

**Comment by adamwoodnz** [comment] 2024-02-01 01:28
Fixed in https://github.com/WordPress/wporg-developer/pull/469

**Closed as completed by adamwoodnz** 2024-02-01 01:28 UTC
Labels: layout, Redesign
