### ISSUE TITLE
Code Reference should not include meta details.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#476] opened 2024-01-16 05:12 UTC
Uncovered in https://github.com/WordPress/wporg-mu-plugins/pull/558, a regression introduced in https://github.com/WordPress/wporg-developer/pull/462 led to the displaying of more meta info than initial launch. 

However, the original designs don't have article metadata. So let's remove it.

Design: https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Resources?node-id=3775%3A11438&mode=dev

Viewing: https://developer.wordpress.org/reference/hooks/block_widgets_no_javascript_message/

| Screenshot |
|--------|
| <img width="875" alt="Screenshot 2024-01-16 at 2 11 23 PM" src="https://github.com/WordPress/wporg-developer/assets/1657336/7ba96fef-a790-46f3-97f8-5b3bdfcad738"> |

**Comment by ryelle** [comment] 2024-01-16 15:25
This is a duplicate of #473 (which should be fixed by #472 👍🏻 )

**Closed as not planned by ryelle** 2024-01-16 15:25 UTC
