### ISSUE TITLE
The Chapter List is not displaying in the correct order in some handbooks

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#409] opened 2023-11-27 12:37 UTC
The chapter list is not always in the same order on the staging site as it is on the current site. A good example is the [Rest API Handbook](https://developer.wordpress.org/redesign-test/rest-api/). It looks like the list is defaulting to alphabetical order. 

Not sure if this is a quirk of the staging site, or a larger issue, but we will need to correct ordering for launch. 

| Redesign | Current Site |
|-|-|
|<img width="328" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/5c3dca37-3b20-4af0-84dd-bb38c75eb7ba">|<img width="316" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/434dbdc2-cd47-40ea-bbb2-30ccd83eae6a">|

The same is true for:

- https://developer.wordpress.org/redesign-test/plugins/
- https://developer.wordpress.org/redesign-test/themes/

Thanks for spotting this @Clorith

**Comment by adamwoodnz** [comment] 2023-11-27 19:35
Duplicate of #391

**Closed as not planned by adamwoodnz** 2023-11-27 19:35 UTC
Labels: Redesign, priority: medium

**Comment by ndiego** [comment] 2023-11-27 19:49
> Duplicate of https://github.com/WordPress/wporg-developer/issues/391

Oops! Thanks
