### ISSUE TITLE
ToC is cumbersome, especially when ToC is long

### ISSUE THREAD

**Issue by joyously** [WordPress/wporg-developer#445] opened 2023-12-15 20:14 UTC
Go to https://developer.wordpress.org/reference/classes/wp_query/

I have to make my window at least 1188px wide to get the Table of Contents to open and be on the right.

On narrower windows (my normal is about 1040px), the ToC is closed and inline. There is a **tiny** > to open it (instead of using the friendlier `details` element).

Whether open or closed, the width of the ToC is quite wide. It looks crowded when next to the content on a wider window. 

On the WP Query page on a wide window, the ToC is longer than my window is high, so I can't scroll it to click the last few links (like Source or User Notes), which is the whole point of having the ToC.

**Comment by ndiego** [comment] 2023-12-16 17:35
Thanks for reporting @joyously 

> There is a tiny > to open it (instead of using the friendlier details element).

This issue has been reported [here](https://github.com/WordPress/wporg-developer/issues/434). 

> On the WP Query page on a wide window, the ToC is longer than my window is high, so I can't scroll it to click the last few links (like Source or User Notes), which is the whole point of having the ToC.

Yes, I am seeing the same thing on a small browser window. In this situation, I think the TOC should scroll independently. The [React Docs](https://react.dev/learn/tutorial-tic-tac-toe) have a similar implementation that we could use as inspiration. 

![react-toc](https://github.com/WordPress/wporg-developer/assets/4832319/c70facfa-6b34-4e0d-817a-602fb69620d6)

**Comment by ndiego** [comment] 2023-12-16 17:35
cc @jasmussen @fcoveram for TOC design thoughts.

**Comment by StevenDufresne** [comment] 2023-12-18 03:00
> On the WP Query page on a wide window, the ToC is longer than my window is high, **so I can't scroll it** to click the last few links (like Source or User Notes), which is the whole point of having the ToC.

When the Table of Contents is longer than the window height, it shouldn't be fixed. Is it currently fixed?

It should look like this:

![Screen Capture on 2023-12-18 at 11-57-38 (1)](https://github.com/WordPress/wporg-developer/assets/1657336/3e70ec19-e269-4592-a474-7ffa8fa66f36)

**Comment by joyously** [comment] 2023-12-18 04:04
My browser is Firefox 121.0 on Ubuntu 22.04. On a wide window, the ToC is stationary and the content is scrolled.
![Peek 2023-12-17 22-01](https://github.com/WordPress/wporg-developer/assets/7957680/d2450a1b-b8b5-4285-8c05-966f6632dc35)

**Comment by fcoveram** [comment] 2023-12-18 11:18
> I have to make my window at least 1188px wide to get the Table of Contents to open and be on the right… Whether open or closed, the width of the ToC is quite wide. It looks crowded when next to the content on a wider window.

If I remember correctly, @jasmussen @ndiego and I talked about this when revisiting the layout. In this [mockup note](https://share.cleanshot.com/lpcpCS9D), available in the designs, we discussed above placing the TOC out of the main content wrapper so TOC's margin-right is tighter, and therefore, it changes to inline in a smaller viewport.

The white space on the right is currently caused by an [empty padding](https://share.cleanshot.com/J3dDY3x4) and [empty margin](https://share.cleanshot.com/g7FXgKnM) on the right.

> On the WP Query page on a wide window, the ToC is longer than my window is high, so I can't scroll it to click the last few links (like Source or User Notes), which is the whole point of having the ToC.

I think we can address this from the content rather than removing H3 headings. "Parameters" is the longest section with multiple H3 headings. Does it need to be like that? If so, does it make sense to move all that content to a new post?

The above should not stop us from implementing the scrollable TOC like in @ndiego's example from React Docs, but a copy review may solve this issue as long posts sometimes require a scope reivisit.

**Comment by ndiego** [comment] 2023-12-18 13:09
> I think we can address this from the content rather than removing H3 headings. "Parameters" is the longest section with multiple H3 headings. Does it need to be like that? 

Yup, this is documentation for `WP_Query`, and it all needs to live on that one page. We are going to run into situations like this a lot in the developer docs, so I think we should ensure the TOC can efficiently support this setup. There are definitely copy improvements that can be made throughout, but it will be quicker to modify the TOC to support these situations 😅

**Comment by ndiego** [comment] 2023-12-18 13:20
I did a bit of testing, and I think the issue is the scroll/sticky nature of the TOC does not take into account manual resizing of the browser window. 

In the video below, I start with a large browser window and the TOC is sticky. I then manually make the window small, and the TOC remains sticky and I cannot see the bottom portion of it. 

However, when I refresh the page, the TOC is not sticky (as expected due to the window size). When I make the window large again, the TOC remains fixed at the top of the page and scrolls with the content.

So perhaps we just need to detect if the window has been resized?

https://github.com/WordPress/wporg-developer/assets/4832319/8b926764-bce8-476f-8a84-3a7a55cbbfe6

**Comment by joyously** [comment] 2023-12-18 17:20
Somehow, the test with resizing the window seems opposite of what I experience.
My window is normally about 1040px, so the first load shows the ToC inline. Making the window larger to get the ToC on the right leaves me with a sticky ToC that I can't scroll.

**Comment by jasmussen** [comment] 2023-12-19 08:53
Agreed this needs to be addressed, though I think it's largely captured in this followup: https://github.com/WordPress/wporg-developer/issues/365#issuecomment-1812025099

That is to say, the TOC should be sticky, and scroll independently if need be.

**Comment by adamwoodnz** [comment] 2024-02-01 01:33
These issues have been addressed in https://github.com/WordPress/wporg-developer/pull/469

Included in this is a resize handler, so changing the screen size after page load or changing orientation should work now.

Please let us know if problems persist.

There is also a related [issue for the ToC breakpoint](https://github.com/WordPress/wporg-mu-plugins/issues/566) open and in discussion.

**Closed as completed by adamwoodnz** 2024-02-01 01:33 UTC
Labels: [Status] Needs Design Feedback, Redesign, priority: high
